# Generated by Django 4.2.7 on 2025-03-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="is_polished",
            field=models.BooleanField(default=False),
        ),
    ]
