# Generated by Django 4.2.7 on 2025-03-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0002_journalentry_is_polished"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalentry",
            name="date_posted",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
