# Generated by Django 4.2.7 on 2025-03-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0004_journalentry_diff_html_journalentry_evaluation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalentry",
            name="topic",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
