# Generated by Django 4.2.1 on 2025-03-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0005_alter_journalentry_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="markdown_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
