# Generated by Django 4.2.1 on 2025-03-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0007_tag_journalentry_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="polish_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="topic",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
